/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentRegistry,
  IAgentRegistryInterface,
} from "../../../contracts/interfaces/IAgentRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "inftTokenId",
        type: "uint256",
      },
    ],
    name: "AgentRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum IAgentRegistry.AgentStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "AgentStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "executionId",
        type: "bytes32",
      },
    ],
    name: "ExecutionTriggered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    name: "getAgent",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "inftTokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "strategyExecutor",
            type: "address",
          },
          {
            internalType: "enum IAgentRegistry.AgentStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "strategyHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IAgentRegistry.Agent",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "inftTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "strategyExecutor",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "strategyHash",
        type: "bytes32",
      },
    ],
    name: "registerAgent",
    outputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "enum IAgentRegistry.AgentStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "setStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "executionParams",
        type: "bytes",
      },
    ],
    name: "triggerExecution",
    outputs: [
      {
        internalType: "bytes32",
        name: "executionId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentRegistryInterface {
    return new Interface(_abi) as IAgentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentRegistry {
    return new Contract(address, _abi, runner) as unknown as IAgentRegistry;
  }
}
