/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAgentRegistry {
  export type AgentStruct = {
    inftTokenId: BigNumberish;
    owner: AddressLike;
    strategyExecutor: AddressLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    strategyHash: BytesLike;
  };

  export type AgentStructOutput = [
    inftTokenId: bigint,
    owner: string,
    strategyExecutor: string,
    status: bigint,
    createdAt: bigint,
    strategyHash: string
  ] & {
    inftTokenId: bigint;
    owner: string;
    strategyExecutor: string;
    status: bigint;
    createdAt: bigint;
    strategyHash: string;
  };
}

export interface IAgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAgent"
      | "registerAgent"
      | "setStatus"
      | "triggerExecution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentStatusChanged"
      | "ExecutionTriggered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerExecution",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "triggerExecution",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    inftTokenId: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    inftTokenId: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    inftTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [agentId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [agentId: bigint, status: bigint];
  export interface OutputObject {
    agentId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionTriggeredEvent {
  export type InputTuple = [agentId: BigNumberish, executionId: BytesLike];
  export type OutputTuple = [agentId: bigint, executionId: string];
  export interface OutputObject {
    agentId: bigint;
    executionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [IAgentRegistry.AgentStructOutput],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [
      inftTokenId: BigNumberish,
      strategyExecutor: AddressLike,
      strategyHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  setStatus: TypedContractMethod<
    [agentId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  triggerExecution: TypedContractMethod<
    [agentId: BigNumberish, executionParams: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [IAgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      inftTokenId: BigNumberish,
      strategyExecutor: AddressLike,
      strategyHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStatus"
  ): TypedContractMethod<
    [agentId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "triggerExecution"
  ): TypedContractMethod<
    [agentId: BigNumberish, executionParams: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionTriggered"
  ): TypedContractEvent<
    ExecutionTriggeredEvent.InputTuple,
    ExecutionTriggeredEvent.OutputTuple,
    ExecutionTriggeredEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(uint256,address,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusChanged(uint256,uint8)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "ExecutionTriggered(uint256,bytes32)": TypedContractEvent<
      ExecutionTriggeredEvent.InputTuple,
      ExecutionTriggeredEvent.OutputTuple,
      ExecutionTriggeredEvent.OutputObject
    >;
    ExecutionTriggered: TypedContractEvent<
      ExecutionTriggeredEvent.InputTuple,
      ExecutionTriggeredEvent.OutputTuple,
      ExecutionTriggeredEvent.OutputObject
    >;
  };
}
