/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC7857 {
  export type AgentMetadataStruct = {
    metadataHash: BytesLike;
    lastUpdated: BigNumberish;
    authorizedUpdater: AddressLike;
  };

  export type AgentMetadataStructOutput = [
    metadataHash: string,
    lastUpdated: bigint,
    authorizedUpdater: string
  ] & { metadataHash: string; lastUpdated: bigint; authorizedUpdater: string };
}

export interface IERC7857Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAgentMetadata"
      | "mintAgent"
      | "setExecutor"
      | "updateMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExecutorUpdated" | "MetadataUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgentMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAgent",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAgentMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;
}

export namespace ExecutorUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, executor: AddressLike];
  export type OutputTuple = [tokenId: bigint, executor: string];
  export interface OutputObject {
    tokenId: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    newHash: BytesLike,
    updater: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, newHash: string, updater: string];
  export interface OutputObject {
    tokenId: bigint;
    newHash: string;
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC7857 extends BaseContract {
  connect(runner?: ContractRunner | null): IERC7857;
  waitForDeployment(): Promise<this>;

  interface: IERC7857Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgentMetadata: TypedContractMethod<
    [tokenId: BigNumberish],
    [IERC7857.AgentMetadataStructOutput],
    "view"
  >;

  mintAgent: TypedContractMethod<
    [to: AddressLike, initialMetadataHash: BytesLike, executor: AddressLike],
    [bigint],
    "nonpayable"
  >;

  setExecutor: TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;

  updateMetadata: TypedContractMethod<
    [tokenId: BigNumberish, newMetadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgentMetadata"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IERC7857.AgentMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintAgent"
  ): TypedContractMethod<
    [to: AddressLike, initialMetadataHash: BytesLike, executor: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExecutor"
  ): TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMetadata"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newMetadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExecutorUpdated"
  ): TypedContractEvent<
    ExecutorUpdatedEvent.InputTuple,
    ExecutorUpdatedEvent.OutputTuple,
    ExecutorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;

  filters: {
    "ExecutorUpdated(uint256,address)": TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;
    ExecutorUpdated: TypedContractEvent<
      ExecutorUpdatedEvent.InputTuple,
      ExecutorUpdatedEvent.OutputTuple,
      ExecutorUpdatedEvent.OutputObject
    >;

    "MetadataUpdated(uint256,bytes32,address)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
  };
}
